### ISSUE TITLE
Lint comments

### ISSUE THREAD

**Issue by SlieT** [gepoch/linter-write-good#21]
Is there any way to lint comments? Except from copy and pasting them into the readme file?

Best Regards
SlieT

**Comment by gepoch** [comment]
@SlieT unfortunately no. This is due to the way that Atom applies linters. Basically, if you are editing something that is text-like ([using one of the allowed linter-write-good syntax grammars]( https://github.com/gepoch/linter-write-good/blob/master/lib/init.coffee#L52)) then atom invokes the linter.

In order to make it run against your comments, we'd need to add your languages grammar to the list, but it's all or nothing unfortunately. Write-good would be executed against every line of your source code, which would probably create a to of extraneous noise. Unfortunately it's currently not possibly to only lint specific lines.

In emacs there was a multi-major-mode system that could do things like this, but to my knowledge, nothing like this yet exists in Atom.
