### ISSUE TITLE
Exclude for code blocks

### ISSUE THREAD

**Issue by heyarne** [gepoch/linter-write-good#29]
It is a bit annoying that code blocks are also linted as prose. Is there an option to exclude this?

**Comment by gepoch** [comment]
Unfortunately no. This linter just wraps the upstream https://github.com/btford/write-good which doesn't handle this, and the Atom linter system has no solution for limiting the scope of where a linter runs.

**Comment by envygeeks** [comment]
@gepoch there must be a way to do it, considering that one of the official linters (tidy) has support for scopes: https://github.com/AtomLinter/linter-tidy, wrapping around something else doesn't prevent you from using scopes, and it seems neither does being inside of AtomLinter.

**Comment by gepoch** [comment]
Are you referring to the "grammarScopes" setting in that package? 

grammarScopes just decides what file types the linter applies to. It doesn't control any higher-resolution application of the linter, unfortunately.

From the [linter docs](http://steelbrain.me/linter/types/standard-linter-v2.html):

> grammarScopes is an array of scopes your Linter provider should be invoked on. To determine the proper value, put your cursor in an editor in a location where you expect your provider to activate and run Editor: Log Cursor Scope from the Atom Command Palette, you’ll get a list of scopes, one of which should start with “source”. Choose the most specific source.___ entry as what you use in grammarScopes. If your base linter is able to handle multiple types of files, enter each scope individually in the array.

Notice the scope starts with "source._" That's the language level grammar. You can't specify anything narrower. If you try to set grammarScopes to something more specific, it doesn't work.

At any rate, if you look at the tidy linter source, it's working in the same way that linter-write-good works. It just invokes the upstream linter on the **entire file** and then marshals the output into a data structure so that linter can parse an display it. This package is just a bridge to the write-good library, and that remains the best place to address the issue.
